### create
POST localhost:8080/lucky-accounts
Content-Type: application/json

{
  "userId": "1",
  "roomId": "kiworkshop",
  "amount": "100000",
  "withdrawLimit": "4"
}

### withdraw
GET localhost:8080/lucky-accounts/withdraw
Content-Type: application/json

{
  "token": "f7f",
  "roomId": "kiworkshop",
  "userId": "6"
}

### lookup
GET localhost:8080/lucky-accounts/lookup
Content-Type: application/json

{
  "token": "f7f",
  "userId": "1"
}