### create
POST localhost:8080/lucky-accounts
Content-Type: application/json

{
  "userId": "2",
  "roomId": "kiworkshop",
  "amount": "100000",
  "withdrawLimit": "4"
}

### withdraw
GET localhost:8080/lucky-accounts/withdraw
Content-Type: application/json

{
  "token": "3ea",
  "roomId": "kiworkshop",
  "userId": "5"
}

### lookup
GET localhost:8080/lucky-accounts/lookup
Content-Type: application/json

{
  "token": "c64",
  "userId": "2"
}