### create
POST localhost:8080/lucky-accounts
Content-Type: application/json

{
  "userId": "1",
  "roomId": "kiworkshop",
  "amount": "100000",
  "withdrawLimit": "4"
}

### get
GET localhost:8080/lucky-accounts
Content-Type: application/json

{
  "token": "836",
  "roomId": "kiworkshop",
  "userId": "6"
}